package com.campus.recruit_recommend.model;
// Generated 2016-11-1 20:38:43 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TRecruitRecommend generated by hbm2java
 */
@Entity
@Table(name = "t_recruit_recommend", catalog = "jobspace")
public class TRecruitRecommend implements java.io.Serializable {

	private Integer id;
	private int recommendTime;
	private int studentId;
	private Integer recruitId;
	private int viewCount;
	private float remarker;

	public TRecruitRecommend() {
	}

	public TRecruitRecommend(int recommendTime, int studentId, int viewCount, float remarker) {
		this.recommendTime = recommendTime;
		this.studentId = studentId;
		this.viewCount = viewCount;
		this.remarker = remarker;
	}

	public TRecruitRecommend(int recommendTime, int studentId, Integer recruitId, int viewCount, float remarker) {
		this.recommendTime = recommendTime;
		this.studentId = studentId;
		this.recruitId = recruitId;
		this.viewCount = viewCount;
		this.remarker = remarker;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "recommend_time", nullable = false)
	public int getRecommendTime() {
		return this.recommendTime;
	}

	public void setRecommendTime(int recommendTime) {
		this.recommendTime = recommendTime;
	}

	@Column(name = "student_id", nullable = false)
	public int getStudentId() {
		return this.studentId;
	}

	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	@Column(name = "recruit_id")
	public Integer getRecruitId() {
		return this.recruitId;
	}

	public void setRecruitId(Integer recruitId) {
		this.recruitId = recruitId;
	}

	@Column(name = "view_count", nullable = false)
	public int getViewCount() {
		return this.viewCount;
	}

	public void setViewCount(int viewCount) {
		this.viewCount = viewCount;
	}

	@Column(name = "remarker", nullable = false, precision = 12, scale = 0)
	public float getRemarker() {
		return this.remarker;
	}

	public void setRemarker(float remarker) {
		this.remarker = remarker;
	}

}
