package com.campus.resume_recommend.model;
// Generated 2016-11-1 0:54:57 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TResumeRecommend generated by hbm2java
 */
@Entity
@Table(name = "t_resume_recommend", catalog = "jobspace")
public class TResumeRecommend implements java.io.Serializable {

	private Integer recommendId;
	private int recommendTime;
	private int resumeId;
	private int recruitId;
	private int viewCount;
	private float remarker;

	public TResumeRecommend() {
	}

	public TResumeRecommend(int recommendTime, int resumeId, int recruitId, int viewCount, float remarker) {
		this.recommendTime = recommendTime;
		this.resumeId = resumeId;
		this.recruitId = recruitId;
		this.viewCount = viewCount;
		this.remarker = remarker;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "recommend_id", unique = true, nullable = false)
	public Integer getRecommendId() {
		return this.recommendId;
	}

	public void setRecommendId(Integer recommendId) {
		this.recommendId = recommendId;
	}

	@Column(name = "recommend_time", nullable = false)
	public int getRecommendTime() {
		return this.recommendTime;
	}

	public void setRecommendTime(int recommendTime) {
		this.recommendTime = recommendTime;
	}

	@Column(name = "resume_id", nullable = false)
	public int getResumeId() {
		return this.resumeId;
	}

	public void setResumeId(int resumeId) {
		this.resumeId = resumeId;
	}

	@Column(name = "recruit_id", nullable = false)
	public int getRecruitId() {
		return this.recruitId;
	}

	public void setRecruitId(int recruitId) {
		this.recruitId = recruitId;
	}

	@Column(name = "view_count", nullable = false)
	public int getViewCount() {
		return this.viewCount;
	}

	public void setViewCount(int viewCount) {
		this.viewCount = viewCount;
	}

	@Column(name = "remarker", nullable = false, precision = 12, scale = 0)
	public float getRemarker() {
		return this.remarker;
	}

	public void setRemarker(float remarker) {
		this.remarker = remarker;
	}

}
